var fips = {
    "Alabama": "01",
    "Alaska": "02",
    "Arizona": "04",
    "Arkansas": "05",
    "California": "06",
    "Colorado": "08",
    "Connecticut": "09",
    "Delaware": "10",
    "District of Columbia": "11",
    "Florida": "12",
    "Georgia": "13",
    "Hawaii": "15",
    "Idaho": "16",
    "Illinois": "17",
    "Indiana": "18",
    "Iowa": "19",
    "Kansas": "20",
    "Kentucky": "21",
    "Louisiana": "22",
    "Maine": "23",
    "Maryland": "24",
    "Massachusetts": "25",
    "Michigan": "26",
    "Minnesota": "27",
    "Mississippi": "28",
    "Missouri": "29",
    "Montana": "30",
    "Nebraska": "31",
    "Nevada": "32",
    "New Hampshire": "33",
    "New Jersey": "34",
    "New Mexico": "35",
    "New York": "36",
    "North Carolina": "37",
    "North Dakota": "38",
    "Ohio": "39",
    "Oklahoma": "40",
    "Oregon": "41",
    "Pennsylvania": "42",
    "Rhode Island": "44",
    "South Carolina": "45",
    "South Dakota": "46",
    "Tennessee": "47",
    "Texas": "48",
    "Utah": "49",
    "Vermont": "50",
    "Virginia": "51",
    "Washington": "53",
    "West Virginia": "54",
    "Wisconsin": "55",
    "Wyoming": "56"
};

var statehood = {
    "Delaware": percentageOfTweets.Delaware,
    "Pennsylvania": percentageOfTweets.Pennsylvania,
    "New Jersey": percentageOfTweets.New_Jersey,
    "Georgia": percentageOfTweets.Georgia,
    "Connecticut": percentageOfTweets.Connecticut,
    "Massachusetts": percentageOfTweets.Massachusetts,
    "Maryland": percentageOfTweets.Maryland,
    "South Carolina": percentageOfTweets.South_Carolina,
    "New Hampshire": percentageOfTweets.New_Hampshire,
    "Virginia": percentageOfTweets.Virginia,
    "New York": percentageOfTweets.New_York,
    "North Carolina": percentageOfTweets.North_Carolina,
    "Rhode Island": percentageOfTweets.Rhode_Island,
    "Vermont": percentageOfTweets.Vermont,
    "Kentucky": percentageOfTweets.Kentucky,
    "Tennessee": percentageOfTweets.Tennessee,
    "Ohio": percentageOfTweets.Ohio,
    "Louisiana": percentageOfTweets.Louisiana,
    "Indiana": percentageOfTweets.Indiana,
    "Mississippi": percentageOfTweets.Mississippi,
    "Illinois": percentageOfTweets.Illinois,
    "Alabama": percentageOfTweets.Alabama,
    "Maine": percentageOfTweets.Maine,
    "Missouri": percentageOfTweets.Missouri,
    "Arkansas": percentageOfTweets.Arkansas,
    "Michigan": percentageOfTweets.Michigan,
    "Florida": percentageOfTweets.Florida,
    "Texas": percentageOfTweets.Texas,
    "Iowa": percentageOfTweets.Iowa,
    "Wisconsin": percentageOfTweets.Wisconsin,
    "California": percentageOfTweets.California,
    "Minnesota": percentageOfTweets.Minnesota,
    "Oregon": percentageOfTweets.Oregon,
    "Kansas": percentageOfTweets.Kansas,
    "West Virginia": percentageOfTweets.West_Virginia,
    "Nevada": percentageOfTweets.Nevada,
    "Nebraska": percentageOfTweets.Nebraska,
    "Colorado": percentageOfTweets.Colorado,
    "North Dakota": percentageOfTweets.North_Dakota,
    "South Dakota": percentageOfTweets.South_Dakota,
    "Montana": percentageOfTweets.Montana,
    "Washington": percentageOfTweets.Washington,
    "Idaho": percentageOfTweets.Idaho,
    "Wyoming": percentageOfTweets.Wyoming,
    "Utah": percentageOfTweets.Utah,
    "Oklahoma": percentageOfTweets.Oklahoma,
    "New Mexico": percentageOfTweets.New_Mexico,
    "Arizona": percentageOfTweets.Arizona,
    "Alaska": percentageOfTweets.Alaska,
    "Hawaii": percentageOfTweets.Hawaii
};

// Parse dates and convert to FIPS codes.
var states = {};
for (var state in statehood) {
    states[fips[state]] = new Number(statehood[state]);
}
